# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TGIF' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FirebaseMessaging'
  # Pods for TGIF

  target 'TGIF-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TGIFTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TGIF-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TGIF-tvOS

  target 'TGIF-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
